spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/good-choice'
    username: 'good-choice-user'
    password: 'good-choice-pass'

server.port: 8080

good-choice:
  bootstrap:
    employee-creation:
      enabled: true
      accounts:
        - role: 'hr'
          email: 'goodchoice.hr.super.local@gmail.com'
          first-name: 'HR'
          last-name: 'Super Local'
          password: 'password'
        - role: 'moderator'
          email: 'goodchoice.moderator.super.local@gmail.com'
          first-name: 'Moderator'
          last-name: 'Super Local'
          password: 'password'
        - role: 'administrator'
          email: 'goodchoice.administrator.super.local@gmail.com'
          first-name: 'Administrator'
          last-name: 'Super Local'
          password: 'password'

  email:
    mode: 'emulation'
    bot:
      name: 'GoodChoice Local Bot'
      address: 'goodchoice.bot.local@gmail.com'
    help:
      name: 'GoodChoice Local Help'
      address: 'goodchoice.help.local@gmail.com'
