spring:
  application:
    name: 'good-choice'

  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: '${JDBC_DATABASE_URL}'
    username: '${JDBC_DATABASE_USERNAME}'
    password: '${JDBC_DATABASE_PASSWORD}'

  jooq.sql-dialect: 'postgres'

  mail:
    host: '${MAIL_HOST:smtp.gmail.com}'
    port: ${MAIL_PORT:587}
    username: '${MAIL_USERNAME}'
    password: '${MAIL_PASSWORD}'
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          writetimeout: 5000

springdoc:
  packages-to-scan: 'com.goodchoice.rest'
  api-docs:
    path: '/docs'
  swagger-ui:
    path: '/'
    display-request-duration: true
    operationsSorter: 'method'
  show-login-endpoint: true

server.port: ${PORT:443}

good-choice:
  email:
    mode: 'real'
    bot:
      address: '${spring.mail.username}'
      name: 'GoodChoice Bot'
    help:
      address: '${spring.mail.username}'
      name: 'GoodChoice Help'
