spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/good-choice'
    username: 'good-choice-user'
    password: 'good-choice-pass'

server.port: 8080

good-choice:
  services:
    webFrontend: 'http://localhost:4200'

  email:
    bot.name: 'GoodChoice Local Bot'
    help.name: 'GoodChoice Local Help'
