spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/good-choice'
    username: 'good-choice-user'
    password: 'good-choice-pass'

server.port: 8080

good-choice:
  email:
    mode: 'emulation'
    bot:
      name: 'GoodChoice Local Bot'
      address: 'goodchoice.bot.local@gmail.com'
    help:
      name: 'GoodChoice Local Help'
      address: 'goodchoice.help.local@gmail.com'
