name: good-choice-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres-pass
        ports:
          - 5432:5432
        volumes:
          - ${{ github.workspace }}/local/initdb:/docker-entrypoint-initdb.d
          # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - run: sudo chown -R $USER:$USER /home/github/actions-runner/_work/good-choice
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build application
        run: ./gradlew build -x test
      - name: Test application
        run: ./gradlew test
