name: good-choice-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Pull Postgres Docker image
        run: docker pull bitnami/postgresql:13.2.0-debian-10-r45
      - name: Create Postgres Docker container
        run: >
          docker create
          --name good-choice-db-postgres
          -e POSTGRES_PASSWORD=postgres-pass
          -e POSTGRES_INITDB_ARGS="--encoding=UTF8"
          -p 5432:5432
          -v ${{ github.workspace }}/local/initdb:/docker-entrypoint-initdb.d
          bitnami/postgresql:13.2.0-debian-10-r45
      - name: Start Postgres Docker container
        run: docker start good-choice-db-postgres
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build application
        run: ./gradlew build -x test
      - name: Test application
        run: ./gradlew test
